# Рабочая тетрадь 2
## Кармазин Вадим Сергеевич

<img src="https://www.icegif.com/wp-content/uploads/icegif-65.gif">

### Библиотека NumPy
```
    NumPy (NumericalPython) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.
    Если у вас уже есть Python, вы можете установить NumPy с помощью командной строки:
    - pip install numpy
    Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:
    import numpy as np
    Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.
    Наиболее важные атрибуты объектов ndarray:
    ndarray.ndim - число измерений (чаще их называют "оси") массива.
    ndarray.shape - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
    ndarray.size - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
    ndarray.dtype - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том
числе и составные.
    ndarray.itemsize - размер каждого элемента массива в байтах.
    ndarray.data - буфер, содержащий фактические элементы массива.
    Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов. Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html
```

***Пример:*** Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [2]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


***Пример:*** Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [4]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


***Пример:*** Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

In [25]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.004134855049344854 0.9915161254457177 0.4882140246090273


***Пример:*** Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [8]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


***Пример:*** Выяснить результат следующих выражений:</br>
0 * np.nan</br>
np.nan == np.nan</br>
np.inf > np.nan</br>
np.nan - np.nan</br>
0.3 == 3 * 0.1

In [9]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


***Пример:*** Отсортировать массив.

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


***Задание:*** Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами

In [17]:
A = np.zeros((8, 8), dtype = int)
A[1::2, ::2] = 1
A[::2, 1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


***Задача:*** Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange

In [26]:
A = np.zeros((5, 5) dtype = int)
print(A)

[0 1 2 3 4]
