# Рабочая тетрадь 2
## Кармазин Вадим Сергеевич

<img src="https://www.icegif.com/wp-content/uploads/icegif-65.gif">

### Библиотека NumPy
```
    NumPy (NumericalPython) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.
    Если у вас уже есть Python, вы можете установить NumPy с помощью командной строки:
    - pip install numpy
    Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:
    import numpy as np
    Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.
    Наиболее важные атрибуты объектов ndarray:
    ndarray.ndim - число измерений (чаще их называют "оси") массива.
    ndarray.shape - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
    ndarray.size - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
    ndarray.dtype - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том
числе и составные.
    ndarray.itemsize - размер каждого элемента массива в байтах.
    ndarray.data - буфер, содержащий фактические элементы массива.
    Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов. Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html
```

***Пример:*** Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [1]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


***Пример:*** Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


***Пример:*** Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

In [3]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.001548356963350428 0.9921216529900596 0.4831664324481351


***Пример:*** Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [4]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


***Пример:*** Выяснить результат следующих выражений:</br>
0 * np.nan</br>
np.nan == np.nan</br>
np.inf > np.nan</br>
np.nan - np.nan</br>
0.3 == 3 * 0.1

In [5]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


***Пример:*** Отсортировать массив.

In [6]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


***Задание:*** Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами

In [7]:
A = np.zeros((8, 8), dtype = int)
A[1::2, ::2] = 1
A[::2, 1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


***Задание:*** Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange

In [8]:
Z = np.full(25, 0).reshape((5, 5))
A = np.arange(0, 5)
for i in range (0, 5):
    for j in range (0, 5):
        Z[i, j] = A[j]
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


***Задание:*** Создать массив 3x3x3 со случайными значениями.

In [9]:
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.38115683 0.39302566 0.91466172]
  [0.71145418 0.06572283 0.73947595]
  [0.38204343 0.62927069 0.23265098]]

 [[0.96504748 0.10891136 0.60419308]
  [0.50575631 0.66397925 0.53284483]
  [0.23231347 0.14917862 0.49206721]]

 [[0.35289101 0.33948901 0.07756203]
  [0.68249981 0.53737453 0.63531782]
  [0.79061302 0.77464634 0.81704534]]]


***Задание:*** Создать матрицу с 0 внутри, и 1 на границах.

In [10]:
Z = np.full(100, 0).reshape((10, 10))
Z[0] = 1
Z[9] = 1
Z[1:9, 0] = 1
Z[1:9, 9] = 1
print(Z)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


***Задание:*** Создайте массив и отсортируйте его по убыванию.

In [11]:
Z = np.array([0, 5, 7, 4, 17, 9, -5, 8])
Z = np.sort(Z)
print(Z[::-1])

[17  9  8  7  5  4  0 -5]


***Задание:*** Создайте матрицу, выведите ее форму, размер и размерность.

In [12]:
Z = np.array([[10, -5, 15], [30, -6, 91]])
if (Z.shape[0]==Z.shape[1]):
    print("Матрица квадратная")
else:
    print("Матрица прямоугольная")
print(f"Размер матрицы: {Z.size}")
print(f"Размерность матрицы: {Z.shape}")

Матрица прямоугольная
Размер матрицы: 6
Размерность матрицы: (2, 3)


<img src="https://c.tenor.com/8tOMw6oUlU0AAAAC/giy%C5%ABtomioka-serious.gif">

### Библиотека Pandas
```
    Первым шагом в любом начинании в области машинного обучения
является введение исходных данных в систему. Исходные данные могут
вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких
источников.
    Библиотека pandas – это удобный и быстрый инструмент для работы
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки
зрения использования инструменты для хранения данных и работе с ними.
    Библиотека pandas присутствует в стандартной поставке Anaconda.
Если же ее там нет, то его можно установить отдельно. Для этого введите
командной строке:
   •  pip install pandas
    Для импорта библиотеки используйте команду:
    import pandas as pd
    Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.
    Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.
    DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами.
```

***Пример:*** Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

In [13]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


***Пример:*** Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [14]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


***Пример:*** Создайте новый фрейм данных.

In [15]:
dataframe =pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

***Пример:*** Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [16]:
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

***Пример:*** Пронализировать характеристики фрейма данных.</br>
<hr>
    Одна из самых простых вещей, которые мы можем сделать после загрузки данных, – это взглянуть на первые несколько строк с помощью метода head. На последние строки можно посмотреть с помощью функции tail. Мы также можем взглянуть на количество строк и столбцов: dataframe.shape. Кроме того, используя метод describe, мы можем получить описательную статистику для любых числовых столбцов

In [17]:
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [18]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [19]:
dataframe.shape

(1313, 6)

In [20]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

***Пример:*** Выберите индивидуальные данные или срезы фрейма данных.</br>
<hr>
Для выбора одной или нескольких строк, либо значений, можно
использовать методы 1ос или iloc.

In [21]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

***Пример:*** Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [22]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

***Задание:*** Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу

In [23]:
a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])

print(sum((a-b)**2)**.5)

2.0


***Задание:*** Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).

In [33]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'
dataframe = pd.read_csv(url)
dataframe

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer
5    True     steep   highest    conifer
6    True     steep      high  chapparal

***Задание:*** Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [37]:
dataframe.head(2)

stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian

In [35]:
dataframe.tail(3)

stream  slope elevation vegetation
4   False   flat      high    conifer
5    True  steep   highest    conifer
6    True  steep      high  chapparal

In [38]:
dataframe.shape

(7, 4)

In [39]:
dataframe.describe()

stream  slope elevation vegetation
count       7      7         7          7
unique      2      3         4          3
top      True  steep      high  chapparal
freq        4      5         3          3

In [40]:
dataframe.iloc[1:4]

stream     slope elevation vegetation
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal

In [51]:
dataframe[dataframe['slope'] =='steep']

stream  slope elevation vegetation
0   False  steep      high  chapparal
2    True  steep    medium   riparian
3   False  steep    medium  chapparal
5    True  steep   highest    conifer
6    True  steep      high  chapparal

<img src="https://media2.giphy.com/media/J6JazAkCVLId91L4yM/200.gif">

### Работа с числовыми данными
```
   Количественные данные что-то измеряют – будь то размер класса,
ежемесячные продажи или оценки учащихся. Естественным способом
представления этих величин является численным (например, 150 студентов,
$529 392 продаж)
    Нормализация данных — это общепринятая задача предобработки в
машинном обучении. Многие алгоритмы предполагают, что все признаки
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1. 
   Существует множество способов нормализации значений признаков,
чтобы масштабировать их к единому диапазону и использовать в различных
моделях машинного обучения. В зависимости от используемой функции, их
можно разделить на 2 большие группы: линейные и нелинейные. При
нелинейной нормализации в расчетных соотношениях используются
функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется
пропорционально, по линейному закону.
    На практике наиболее распространены следующие методы
нормализации признаков:
    • Минимакс – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;
    • Z-масштабирование данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.
   При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.
```

***Пример:*** Прошкалируйте числовой признак в диапазон между двумя значениями.

In [78]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing

#Созать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Созать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

#Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

#Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

***Пример:*** Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [57]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Созать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

Мы можем увидеть эффект стандартизации, обратившись к среднему
значению и стандартному отклонению результата нашего решения:

In [58]:
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


***Пример:*** Дан фрейм данных</br>
dfTest = pd.DataFrame({</br>
'A':[14.00,90.20,90.95,96.27,91.21],</br>
 'B':[103.02,107.26,110.35,114.23,114.68],</br>
 'C':['big','small','big','small','small']</br>
 })</br>
Необходимо масштабировать его числовые столбцы.

In [60]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest  = pd.DataFrame({
'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']
})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

***Задание:*** Загрузить фрейм данных по ссылке:</br>
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.</br>
Необходимо выполнить нормализацию первого числового признака</br>
(sepal_length_cm) с использованием минимаксного преобразования, а</br>
второго (sepal_width_cm) с задействованием z-масштабирования

In [100]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
minmax_scale = preprocessing.MinMaxScaler()
dataframe[['sepal_length_cm']] = minmax_scale.fit_transform(dataframe[['sepal_length_cm']])
print(dataframe['sepal_width_cm'].mean)
dataframe.head(5)

<bound method NDFrame._add_numeric_operations.<locals>.mean of 0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width_cm, Length: 150, dtype: float64>


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222             3.5              1.4             0.2  setosa
1         0.166667             3.0              1.4             0.2  setosa
2         0.111111             3.2              1.3             0.2  setosa
3         0.083333             3.1              1.5             0.2  setosa
4         0.194444             3.6              1.4             0.2  setosa